### PR TITLE
Separate & Optimize builds

### PR DESCRIPTION
**Pull request by lukeed**
Each application was extracted to its own entry point & then compiled down to an application bundle. This ensures that each app is minified & compiled the same / fairly, while also removing dead code blocks.

Also, as individual entry points, further optimizations can be made to specific apps (I may have missed all optimizations?) and/or future apps.

Before this PR, each test was serving the development builds, which are extremely varying & often unfair. It's also not production-like.

Buble was used because none of the apps required any special preset (eg, `stage-0`).

For what it's worth, these are my results with node `6.9.1`

screen shot 2017-01-17 at 9 48 32 am

> Edit: Updated screenshot after upgrading `preact-render-to-string`.

### CODE REVIEW

**Comment by developit** [comment]
Just adding my 2 cents here - this is a solid change and I think helps model real-world usage even pretty accurately. It even caught a little regression in preact-render-to-string 3.4.0! (since fixed)

**Comment by lukeed** [comment]
Hey @aweary, is there any issue with this that I need to address?

**Comment by aweary** [comment]
Hey @lukeed! I actually didn't see this PR for some reason, thanks for pinging me. This looks good to me, thank you for doing this.

**Review by aweary — APPROVED** [review]

**Comment by lukeed** [comment]
Great! Thanks 😄

**Pull request merged**
